package homelands

import "equipment"

var HomelandsNames = [...]string{"The Drippy Downs", "Fleabag County", "The Quagmash", "River Country", "Scalawag Strand", "The Used T'be Forest", "The Dingledell", "The Underlands"}

type Homeland struct {
	Name          string
	Proficiencies []string
	Equipment     []equipment.Equipment
}

var Homelands = map[string]Homeland{"The Drippy Downs": {Name: "The Drippy Downs",
	Proficiencies: []string{"Hunting", "Climbing", "Jumping", "Cooking"},
	Equipment: []equipment.Equipment{{Name: "Bear Trap", Cost: "Cheap", Slots: 1, Carried: true},
		{Name: "Knife (Bladed)", Cost: "Cheap", Slots: 1, Carried: true},
		{Name: "Bedroll (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
		{Name: "Umbrella (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
		{Name: "Canteen (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
		{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"Fleabag County": {Name: "Fleabag County",
		Proficiencies: []string{"Blending into a Crowd", "Bureaucracy", "Riding", "Writing"},
		Equipment: []equipment.Equipment{{Name: "Change of Fine Clothing (Tool)", Cost: "Pricey", Slots: 1, Carried: true},
			{Name: "Pouch of Silver Coins (Tool)", Cost: "Pricey", Slots: 1, Carried: true},
			{Name: "Pen and Paper (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"The Quagmash": {Name: "The Quagmash",
		Proficiencies: []string{"Fishing", "Gator Wrangling", "Picking Herbs", "Swimming"},
		Equipment: []equipment.Equipment{{Name: "Pend and Paper", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Fishing Gaff (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Fishing Pole (Tool)", Cost: "Cheap", Slots: 2, Carried: true},
			{Name: "Tackle and Bait (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Chum Bucket (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Bug Repellent (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"River Country": {Name: "River Country",
		Proficiencies: []string{"Boating", "Gambling", "Smuggling", "Swimming"},
		Equipment: []equipment.Equipment{{Name: "Overalls (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Overcoat with hidden pockets (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Rope (50') (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Huzzah Deck (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Wooden Oar (Tool)", Cost: "Cheap", Slots: 2, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"Scalawag Strand": {Name: "Scalawag Strand",
		Proficiencies: []string{"Fishing", "Sailing", "Swimming", "Treasure Lore"},
		Equipment: []equipment.Equipment{{Name: "Knife (Bladed)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Compass (Tool)", Cost: "Pricey", Slots: 0, Carried: true},
			{Name: "Rope (50') (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Fishing Pole (Tool)", Cost: "Cheap", Slots: 2, Carried: true},
			{Name: "Tackle and Bait (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"The Used T'be Forest": {Name: "The Used T'be Forest",
		Proficiencies: []string{"Hunting", "Mining", "Repair", "Woodcraft"},
		Equipment: []equipment.Equipment{{Name: "Hatchet (Bladed)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Saw (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Bedroll (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Flint and Tinder (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Stick of Dynamite (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"The Dingledell": {Name: "The Dingledell",
		Proficiencies: []string{"Animal Handling", "Cooking", "Picking Herbs", "Writing"},
		Equipment: []equipment.Equipment{{Name: "Walking Stick (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Pen and Journal (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Whistle (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Animal Feed (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Pot and Pan (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
	"The Underlands": {Name: "The Underlands",
		Proficiencies: []string{"Hiding", "Listening", "Mining", "Seeing in the Dark"},
		Equipment: []equipment.Equipment{{Name: "Lantern (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Pickaxe (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Hard Hat (Tool)", Cost: "Cheap", Slots: 1, Carried: true},
			{Name: "Lantern Oil (Tool)", Cost: "Cheap", Slots: 0, Carried: true},
			{Name: "Rapelling Harness (Tool)", Cost: "Pricey", Slots: 1, Carried: true},
			{Name: "Rations (Tool)", Cost: "Cheap", Slots: 1, Carried: true}}},
}
